notice/urls.py
from django.urls import path,re_path
# 引入views.py
from . import views

app_name = 'notice'

urlpatterns = [
    # 通知列表

re_path(r'^personal/update/$', views.CommentNoticeUpdateView.as_view(), name='readed'),
re_path(r'^personal/message/$',views.Allmessages,name='message'),
]

scrapy_django/urls.py
from django.contrib import admin
from django.urls import re_path,include,path
# from BookList.views import *
import notifications.urls
from django.conf import settings  # 此行是新增
from django.conf.urls.static import static  # 此行是新增
urlpatterns = [
    # re_path(r'^BookList/',include(('BookList.urls','BookList'),namespace='BookList')),
path('admin/', admin.site.urls),
    re_path(r'^', include('web.urls')),
path('ckeditor/', include('ckeditor_uploader.urls')),
   re_path('^inbox/notifications/', include(notifications.urls, namespace='notifications')),
    path('notice/', include('notice.urls', namespace='notice')),
    # path(r'^send/sms/', send_sms),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

web/urls.py
from django.contrib import admin
from django.urls import re_path,path,include
from web.views import account,home,comment,personal
from django.conf import settings
from django.conf.urls.static import static

from django.views.static import serve # 导入媒体文件资源
urlpatterns = [
    re_path(r'^register/$', account.register,name='register'),
re_path(r'^send/email/$', account.send_email,name='send_email'),
    re_path(r'^login/email/$', account.login_email, name='login_email'),
re_path(r'^login/$', account.Login, name='login'),
re_path(r'^image/code/$', account.image_code, name='image_code'),
re_path(r'^index/$',home.Lookbook,name='index'),
re_path(r'^logout/$', account.logout, name='logout'),
re_path(r'^book/(?P<id>\d+)$', home.Bookdetail, name='book_detail'),
re_path(r'^author/(?P<id>\d+)$', home.Authordetail, name='author_detail'),
# ,path('book/<str:id>',home.Bookdetail,name='book_detail')
# path(r'^send/sms/', send_sms),path('detail/<str:name>',Bookdetail,name='detail'),
path('type/<str:type>',home.Type,name='type'),
path('category/<str:category>',home.Category,name='category'),
path('state/<str:state>',home.State,name='state'),
re_path(r'^collection/$',home.Collection,name='collection'),
re_path(r'^popularity/$',home.Popularity,name='popularity'),
re_path(r'^word/$',home.Word,name='word'),

# re_path(r'^rank/(?P<url>\w+)/$',home.Rank,name='rank'),
re_path(r'^rank/word$',home.Rank,name='rank'),
re_path(r'^rank/recommend/$',home.Rank_tuijian,name='tuijian'),
re_path(r'^rank/yuepiao/$',home.Rank_yuepiao,name='yuepiao'),
re_path(r'^rank/vipcollection$',home.Rank_vipcollection,name='vipcollection'),

re_path(r'^end/$',home.End,name='end'),
re_path(r'^free/$',home.Free,name='free'),

re_path(r'^search/$',home.Search,name='search'),

    path('comment/<int:book_id>',comment.Comments , name='comment'),
    re_path(r'^reply/(?P<book_id>\d+)/(?P<parent_comment_id>\d+)/$', comment.Comments, name='reply'),
    # path('reply/<int:book_id>/<int:parent_comment_id>', comment.Comment, name='reply'),
    re_path(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}),
    # 图片文件路径，这里要注意，之前已经在setting.py文件处设置了媒体文件路径的别名是：MEDIA_URL = "/files/" ，所以这里的路由要保持一致




re_path(r'^personal/firstpage/$',personal.FirstPage,name='firstpage'),
# re_path(r'^personal/bookshelf/$',personal.BookShelf,name='bookshelf'),
re_path(r'^personal/bookshelf/$',personal.BookShelf.as_view(),name='bookshelf'),

re_path(r'^personal/mybookcomm/$',comment.my_book_comm,name='mybookcomm'),


re_path(r'^setting/(?P<id>\d+)$',personal.Settings.as_view(),name='setting'),

]
# urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

web/templates/layout/basic.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'plugin/bootstrap/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'plugin/fontawesome/css/font-awesome.min.css' %}">
    <style>
        .red{
            color: #ffffff;
            background-color: #f65b5b;
            margin-left: 15px;
        }
    </style>
    {% block css %}{% endblock %}
</head>
<body>
{% load notice_tag %}


{% load book_info %}
<nav class="navbar navbar-default">
    <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
                    data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url 'index' %}">Novel</a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav">
                {% index_nav request %}
            </ul>
            <form method="post" action="{% url 'search' %}" class="navbar-form navbar-left">
                {% csrf_token %}
                <div class="form-group">
                    <input type="text" class="form-control" placeholder="Search" name="search">
                </div>
                <button type="submit" class="btn btn-default">搜索</button>
            </form>
            <ul class="nav navbar-nav navbar-right">
                {% if request.noval.user %}
                    <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true"
                       aria-expanded="false">
                        {% if request.noval.user|notice_unread %}
                            <svg viewBox="0 0 8 8"
                                 width="8px"
                                 height="8px">
                                <circle cx="4"
                                        cy="4"
                                        r="4"
                                        fill="#ff6b6b"
                                ></circle>
                            </svg>
                        {% endif %}
                        {{ request.noval.user.username }} <span class="caret"></span></a>
                    <ul class="dropdown-menu">
                    <li><a href="{% url 'firstpage' %}">个人中心</a></li>
                    <li><a href="{% url 'notice:message' %}">消息
                        {% if request.noval.user|notice_unread %}
                            <span class="badge badge-danger red" >{{ request.noval.user|notice_unread }}</span>
                        {% endif %}
                    </a></li>
                    <li><a href="{% url 'logout' %}">退出</a></li>
                {% else %}
                    <li><a href="{% url 'login' %}">登录</a></li>
                    <li><a href="{% url 'register' %}">注册</a></li>
                {% endif %}
                </ul>
                </li>
            </ul>
        </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
</nav>

{% block content %}{% endblock %}


<script src="{% static 'js/jquery/jquery-3.4.1.min.js' %}"></script>
<script src="{% static 'plugin/bootstrap/js/bootstrap.min.js' %}"></script>
{% block js %}{% endblock %}
</body>
</html>

web/templates/layout/book_base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title></title>
    <link rel="stylesheet" href="{% static 'plugin/bootstrap/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'plugin/fontawesome/css/font-awesome.min.css' %}">
    {% block css %}{% endblock %}
</head>
<body>
<script src="{% static 'js/jquery/jquery-3.4.1.min.js' %}"></script>
<script src="{% static 'plugin/bootstrap/js/bootstrap.min.js' %}"></script>

</body>
</html>

web/templates/layout/personbase.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'plugin/bootstrap/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'plugin/fontawesome/css/font-awesome.min.css' %}">
    <style>
        .hhh {
            display: flex;
            align-items: center;
            justify-content: center;
        }
    </style>
    {% block css %}{% endblock %}
</head>
<body>

{% load book_info %}
<nav class="hhh navbar navbar-default">
    <div class="container-fluid" style="display:flex;background-color: #ffffff">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
                    data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class=" navbar-brand" href="{% url 'index' %}">Novel</a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class=" collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav">
                {% person_nav request %}
            </ul>

            {#            <ul style="height: 50px;background-color: #0f0f0f">sds</ul>#}
            <ul class="nav navbar-nav navbar-right " style="margin-left: 80px">
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true"
                       aria-expanded="false">{{ request.noval.user.username }} <span class="caret"></span></a>
                    <ul class="dropdown-menu">
                        <li><a href="{% url 'logout' %}">退出</a></li>
                    </ul>
                </li>
            </ul>
        </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
</nav>

{% block content %}{% endblock %}


<script src="{% static 'js/jquery/jquery-3.4.1.min.js' %}"></script>
<script src="{% static 'plugin/bootstrap/js/bootstrap.min.js' %}"></script>
{% block js %}{% endblock %}
</body>
</html>