BookList/urls.py
# from django.contrib import admin
# # from django.conf.urls import url
# from django.urls import re_path,include
# from BookList.views import *
# urlpatterns = [
#     re_path(r'^BookList/register/', Register),
#     # path(r'^send/sms/', send_sms),
# ]

scrapy_django/urls.py
from django.contrib import admin
from django.urls import re_path,include,path
# from BookList.views import *
import notifications.urls
from django.conf import settings  # 此行是新增
from django.conf.urls.static import static  # 此行是新增
urlpatterns = [
    # re_path(r'^BookList/',include(('BookList.urls','BookList'),namespace='BookList')),
path('admin/', admin.site.urls),
    re_path(r'^', include('web.urls')),
path('ckeditor/', include('ckeditor_uploader.urls')),
   re_path('^inbox/notifications/', include(notifications.urls, namespace='notifications')),
    path('notice/', include('notice.urls', namespace='notice')),
    # path(r'^send/sms/', send_sms),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

web/urls.py
from django.contrib import admin
from django.urls import re_path,path,include
from web.views import account,home,comment,personal
from django.conf import settings
from django.conf.urls.static import static

from django.views.static import serve # 导入媒体文件资源
urlpatterns = [
    re_path(r'^register/$', account.register,name='register'),
re_path(r'^send/email/$', account.send_email,name='send_email'),
    re_path(r'^login/email/$', account.login_email, name='login_email'),
re_path(r'^login/$', account.Login, name='login'),
re_path(r'^image/code/$', account.image_code, name='image_code'),
re_path(r'^index/$',home.Lookbook,name='index'),
re_path(r'^logout/$', account.logout, name='logout'),
re_path(r'^book/(?P<id>\d+)$', home.Bookdetail, name='book_detail'),
re_path(r'^author/(?P<id>\d+)$', home.Authordetail, name='author_detail'),
# ,path('book/<str:id>',home.Bookdetail,name='book_detail')
# path(r'^send/sms/', send_sms),path('detail/<str:name>',Bookdetail,name='detail'),
path('type/<str:type>',home.Type,name='type'),
path('category/<str:category>',home.Category,name='category'),
path('state/<str:state>',home.State,name='state'),
re_path(r'^collection/$',home.Collection,name='collection'),
re_path(r'^popularity/$',home.Popularity,name='popularity'),
re_path(r'^word/$',home.Word,name='word'),

# re_path(r'^rank/(?P<url>\w+)/$',home.Rank,name='rank'),
re_path(r'^rank/word$',home.Rank,name='rank'),
re_path(r'^rank/recommend/$',home.Rank_tuijian,name='tuijian'),
re_path(r'^rank/yuepiao/$',home.Rank_yuepiao,name='yuepiao'),
re_path(r'^rank/vipcollection$',home.Rank_vipcollection,name='vipcollection'),

re_path(r'^end/$',home.End,name='end'),
re_path(r'^free/$',home.Free,name='free'),

re_path(r'^search/$',home.Search,name='search'),

    path('comment/<int:book_id>',comment.Comments , name='comment'),
    re_path(r'^reply/(?P<book_id>\d+)/(?P<parent_comment_id>\d+)/$', comment.Comments, name='reply'),
    # path('reply/<int:book_id>/<int:parent_comment_id>', comment.Comment, name='reply'),
    re_path(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}),
    # 图片文件路径，这里要注意，之前已经在setting.py文件处设置了媒体文件路径的别名是：MEDIA_URL = "/files/" ，所以这里的路由要保持一致




re_path(r'^personal/firstpage/$',personal.FirstPage,name='firstpage'),
# re_path(r'^personal/bookshelf/$',personal.BookShelf,name='bookshelf'),
re_path(r'^personal/bookshelf/$',personal.BookShelf.as_view(),name='bookshelf'),

re_path(r'^personal/mybookcomm/$',comment.my_book_comm,name='mybookcomm'),


re_path(r'^setting/(?P<id>\d+)$',personal.Settings.as_view(),name='setting'),

]
# urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

BookList/models.py
from django.db import models

# Create your models here.

# class Authors(models.Model):
#     name=models.CharField(max_length=30,unique=True,primary_key=True)#姓名
#     icon=models.CharField(max_length=255)#头像
#     introduction=models.CharField(max_length=30,default="新人")#简介
#     book_total=models.IntegerField(default=0)#作品数
#     all_word=models.DecimalField(max_length=7,decimal_places=2)#总字数
#     start_work=models.IntegerField(default=0)#创作天数
#
# class Books(models.Model):
#     name=models.CharField(max_length=30,unique=True)#书名
#     author=models.ForeignKey(Authors,on_delete=models.CASCADE,)#作者
#     book_icon=models.CharField(max_length=255)#封面
#     state=models.CharField(max_length=10,default="完结")#书的状态
#     category=models.ForeignKey(Categorys,max_length=30)#书的类型小
#     brief=models.CharField(max_length=255,default='这个人很懒，还没有写简介')
#
# class Categorys(models.Model):
#      category= models.CharField(max_length=30)#书的类型小
#      type = models.CharField(max_length=10)  # 书的种类大

# class UserInfo(models.Model):
#     username = models.CharField(verbose_name='用户名',max_length=30)  # ID
#     password=models.CharField(verbose_name="密码",max_length=10)#密码
#

web/models.py
from django.db import models
from django.contrib.auth.base_user import AbstractBaseUser, BaseUserManager
from django.urls import reverse
# Create your models here.

class Authors(models.Model):
    name = models.CharField(verbose_name='笔名',max_length=30, unique=True)  #
    icon = models.CharField(verbose_name='头像',max_length=255)  #
    introduction = models.CharField(verbose_name='简介',max_length=255, default="新人")  #
    book_total = models.IntegerField(verbose_name='作品数',default=0)  #
    all_word = models.DecimalField(verbose_name='总字数(万)',max_digits=7, decimal_places=2)  #
    start_work = models.IntegerField(verbose_name='创作天数',default=0)  #


# class Categorys(models.Model):
#     type = models.CharField(verbose_name='书的类大',max_length=10)  #
#     category = models.CharField(verbose_name='书的类型小',max_length=30)  #

class Collections(models.Model):
    bookname=models.ForeignKey(verbose_name='书名',to='Books',db_column='bookname',on_delete=models.CASCADE)
    coll_num=models.PositiveIntegerField(verbose_name='收藏数',blank=0)

class Books(models.Model):
    name = models.CharField(verbose_name='书名',max_length=30, unique=True)  #
    author = models.ForeignKey(verbose_name='作者',to='Authors',db_column='author', on_delete=models.CASCADE, )  #
    book_icon = models.CharField(verbose_name='封面',max_length=255)  #
    state = models.BooleanField(verbose_name='状态',default=False)  #flase连载，true完结
    prop_choice = (
        (1, '免费'),
        (2, 'VIP')
    )
    prop=models.SmallIntegerField(verbose_name='属性', choices=prop_choice)
    type = models.CharField(verbose_name='书的种类大', max_length=10)
    category = models.CharField(verbose_name='书的类型小', max_length=30)
    word=models.CharField(verbose_name='字数',max_length=30)
    brief = models.TextField(verbose_name='简介', default='这个人很懒，还没有写简介')
    recommend = models.BigIntegerField(verbose_name='推荐票')

    def get_absolute_url(self):
        return reverse('book_detail', args=[self.id])

class MyViewBook(models.Model):
    #我的书架
    user = models.ForeignKey(verbose_name='用户', to='UserInfo', db_column='user', on_delete=models.CASCADE)
    book = models.ForeignKey(verbose_name='收藏作品', to='Books', db_column='book', on_delete=models.CASCADE)
    collection = models.BooleanField(verbose_name='收藏', default=False)
    time = models.DateTimeField(verbose_name='阅读时间', auto_now_add=True)  # 收藏时间

# class Poll(models.Model):
#     # 投票记录
#     votework=models.ForeignKey(verbose_name='投票作品',to='Books',db_column='votework',on_delete=models.DO_NOTHING)
#     voteuser=models.ForeignKey(verbose_name='投票人',to='UserInfo',db_column='voteuser',on_delete=models.DO_NOTHING)
#     datetime=models.DateTimeField(verbose_name='投票日期')
#     tick_choice = (
#         (1, '推荐票'),
#         (2, '月票')
#     )
#     tick= models.SmallIntegerField(verbose_name='属性', choices=tick_choice)
#


class UserInfo(models.Model):
    username = models.CharField(verbose_name='用户名', max_length=30, db_index=True)
    password = models.CharField(verbose_name="密码", max_length=32)
    email = models.EmailField(verbose_name="邮箱", max_length=30)

class BaseInfo(models.Model):
    # 个人基本信息
    name = models.OneToOneField(verbose_name='用户名', to='UserInfo',db_column='name',on_delete=models.CASCADE)  #
    icon = models.ImageField(verbose_name='头像',upload_to='user/', blank=True) #
    introduction = models.CharField(verbose_name='简介', max_length=255, default="暂无相关介绍")  #
    sex_choice = (
        (1, '男'),
        (2, '女')
    )
    sex = models.SmallIntegerField(verbose_name='性别', choices=sex_choice,default=1)
    gory=models.CharField(verbose_name='地区',max_length=10,)
    level_choice = (
        (1, 'LV1'),
        (2, 'LV2'),
        (3, 'LV3'),
        (4, 'LV4'),
        (5, 'LV5'),

    )
    level = models.SmallIntegerField(verbose_name='等级', choices=level_choice,default=1)
    dianbi=models.PositiveIntegerField(verbose_name='点币')


# class BillFold(models.Model):
#     # 票夹
#     name = models.ForeignKey(verbose_name='用户名', to='UserInfo',db_column='name',on_delete=models.CASCADE)  #
#     recom=models.PositiveIntegerField(verbose_name='推荐票数')
#     month = models.PositiveIntegerField(verbose_name='月票数')

# class Recharge(models.Model):
#     # 充值记录
#     name = models.ForeignKey(verbose_name='用户名', to='UserInfo', db_column='name', on_delete=models.CASCADE)
#     order = models.CharField(verbose_name='订单号', max_length=64, unique=True)  # 唯一索引
#     count = models.IntegerField(verbose_name='充值金额')
#     price = models.IntegerField(verbose_name='实际支付价格')
#     create_datetime = models.DateTimeField(verbose_name='创建时间', auto_now_add=True)

from ckeditor.fields import RichTextField
from ckeditor_uploader.fields import RichTextUploadingField
# django-mptt
from mptt.models import MPTTModel, TreeForeignKey
class Comment(MPTTModel):
    #评论
    user = models.ForeignKey(verbose_name='评论者', to='UserInfo', db_column='user', on_delete=models.CASCADE)
    book = models.ForeignKey(verbose_name='评论作品', to='Books', db_column='book', on_delete=models.DO_NOTHING)

    content= RichTextUploadingField(verbose_name='内容')
    created = models.DateTimeField(verbose_name='创建时间', auto_now_add=True)
    parent = TreeForeignKey('self', on_delete=models.CASCADE, null=True, blank=True, related_name='children')
    # 新增，记录二级评论回复给谁, str
    reply_to = models.ForeignKey(UserInfo, null=True, blank=True, on_delete=models.CASCADE, related_name='replyers')
    class MPTTMeta:
        order_insertion_by = ['created']

    def get_user(self):
        return self.user



class Messages(models.Model):
    sender = models.ForeignKey(UserInfo, on_delete=models.CASCADE, related_name='sender', verbose_name='发送者')
    receiver = models.ForeignKey(UserInfo, on_delete=models.CASCADE, related_name='receiver', verbose_name='接收者')
    create_date = models.DateTimeField('创建时间', auto_now_add = True)
    is_read = models.BooleanField('是否已读', default = False)
    comment = models.ForeignKey(Comment, on_delete=models.CASCADE, related_name='comment', verbose_name='所属评论')

    class Meta:
        verbose_name = '消息通知'
        verbose_name_plural = verbose_name
        ordering = ['-create_date']

    def mark_read(self):
        self.is_read = True
        self.save(update_fields=['is_read'])

web/forms/comment.py
from django import forms
from web.models import Comment
from web.forms.bootstrap import BootStrapForm
from django.core.exceptions import ValidationError



class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['content']

    def clean_content(self):
        content = self.cleaned_data['content']
        if not content:
            raise ValidationError('您还没有输入哦！暂且不能发布！')
        return content

BookList/views.py
# from django.shortcuts import render,HttpResponse
# import random
# # Create your views here.
# from django import forms
# from BookList.models import *
# from django.conf import settings

#
# def send_sms(request):
#     """ 发送短信
#         ?tpl=login  -> 548762
#         ?tpl=register -> 548760
#     """
#     tpl = request.GET.get('tpl')
#     template_id = settings.TENCENT_SMS_TEMPLATE.get(tpl)
#     if not template_id:
#         return HttpResponse('模板不存在')
#
#     code = random.randrange(1000, 9999)
#     res = send_sms_single('15131289', template_id, [code, ])
#     if res['result'] == 0:
#         return HttpResponse('成功')
#     else:
#         return HttpResponse(res['errmsg'])
import redis
from django.shortcuts import render,HttpResponse
from django_redis import get_redis_connection

def index(request):
    conn = get_redis_connection("default")
    conn.set('nickname','lms',ex=10)
    value=conn.get('nickname')
    print(value)
    return HttpResponse('ok')

class RegisterModelFrom(forms.ModelForm):
    password=forms.CharField(label="密码",widget=forms.PasswordInput())
    comfirm_password = forms.CharField(label="重复密码", widget=forms.PasswordInput())
    code=forms.CharField(label="验证码")
    class Meta:
        model=UserInfo
        fields='__all__'
    def __init__(self,*args,**kwargs):
        super().__init__(*args,**kwargs)
        for name,field in self.fields.items():
            field.widget.attrs['class']="form-contorl"
            field.widget.attrs['placeholder'] = "请输入%s"%(field.label)

def Register(request):
    form=RegisterModelFrom()
    return render(request, 'book/register.html', {'form':form})

web/views/comment.py
from django.shortcuts import render, get_object_or_404, redirect

from django.http import HttpResponse, JsonResponse

from web.forms.comment import CommentForm
from web.models import *
from notifications.signals import notify
from django.db.models.signals import post_save
from notifications.signals import notify
from web.models import UserInfo
from django.db.models import Q,F
from django.db.models.signals import post_save
from django.dispatch import receiver

@receiver(post_save, sender=Comment) #只接收comment发来的post_save消息
def create_msg_handler(sender, instance, **kwargs):
    # content = instance.comment  # instance 就是发信号的对象，这里是个评论
    if instance.parent_id:
        sender = instance.user     # 获取评论者，即消息发送者
        receiver = instance.reply_to   # 通知文章作者
        msg = Messages(sender=sender, receiver=receiver, comment=instance)  # 新建消息保存
        msg.save()
def my_handler(sender, instance, book, acomment, **kwargs):
    try:
        notify.send(
            sender=sender,  # 评论者
            recipient=instance,  # 被回复者
            verb='回复了你',
            target=book,
            action_object=acomment,
        )
    except Exception as e:
        print(e)


# from notifications.signals import notify
# from django.contrib.auth.models import User
from django.contrib.auth.models import User
# 文章评论, parent_comment_id=None
from django.views.decorators.csrf import csrf_exempt


@csrf_exempt
def Comments(request, book_id, parent_comment_id=None):
    book = get_object_or_404(Books, id=book_id)
    if request.method == 'GET':
        form = CommentForm()
        context = {
            'comment_form': form,
            'book_id': book_id,
            'parent_comment_id': parent_comment_id
        }
        return render(request, 'comment/reply.html', context)
    print(request.POST)
    # if request.method == 'GET':
    #     form = CommentForm()
    #     context = {
    #             'comment_form': form,
    #             'book_id': book_id,
    #         }
    #     return render(request, 'comment.html', context)
    form = CommentForm(request.POST)
    if form.is_valid():
        acomment = form.save(commit=False)
        acomment.content = request.POST.get('content')
        acomment.book = book
        acomment.user = request.noval.user
        # print(comment,comment.content,comment.book,comment.user)

        # 二级回复
        # if parent_comment_id:
        #     print(parent_comment_id)
        #     parent_comment = Comment.objects.get(id=parent_comment_id)
        #     # 若回复层级超过二级，则转换为二级
        #     acomment.parent_id = parent_comment.get_root().id
        #     # 被回复人
        #     acomment.reply_to = parent_comment.user
        #     acomment.save()
        if parent_comment_id:
            print(parent_comment_id)
            parent_comment = Comment.objects.get(id=parent_comment_id)
            # 若回复层级超过二级，则转换为二级
            acomment.parent_id = parent_comment.get_root().id
            # 被回复人
            acomment.reply_to = parent_comment.user
            acomment.save()

            # 新增代码，给其他用户发送通知
            # 给其他用户发送通知
            # print(isinstance(parent_comment.user,request.noval.user))
            # print('fupinglu', request.user, 'zipingl', request.noval.user)
            # if parent_comment.user == request.user:
            # #     notify.send(request.user,#评论者recipient=parent_comment.user,#被回复者verb='回复了你',target=book,action_object=acomment,)
            #     post_save.connect(, sender=request.noval.user,
            #                       instance=parent_comment.user,
            #                       book=book,
            #                       acomment=acomment)
            #     recipient = request.noval.user
            #     # notify.send(recipient, recipient, verb='New Contact us request')
            #     print('xioaxiokok')
            # # return HttpResponse("200 OK")
            return JsonResponse({"code": "200 OK", "comment_id": acomment.id})

        acomment.save()

        # 添加锚点
        redirect_url = book.get_absolute_url() + '#comment_elem_' + str(acomment.id)
        print('rrrrrrrrrrrrrrrrrrrrrr', redirect_url)
        return redirect(redirect_url)
    else:
        return JsonResponse({'status': False, 'error': form.errors})


def my_book_comm(request):
    comments=Comment.objects.filter(Q(parent_id=None)&Q(user=request.noval.user))
    return render(request,'comment/my_book_comm.html',{'comments':comments})

web/templates/comment.html
{% extends 'layout/basic.html' %}
{% load static %}

{% block title %} 用户登录 {% endblock %}


{% block css %}

{% endblock %}


{% block content %}
    <form method="POST" action=".">
        {% csrf_token %}
        <div class="form-group">
            <label for="content">
                <strong>
                    我也要发言：
                </strong>
            </label>
            <div style="margin-left: 250px">
                {{ comment_form.media }}
                {{ comment_form.content }}
            </div>
        </div>
        <button type="submit" onclick="confirm_submit({{book_id }}, {{ parent_comment_id }})" class="btn btn-primary">发送</button>

    </form>



{% endblock %}


{% block js %}

    <script>
        $(function () {
            $(".django-ckeditor-widget").removeAttr('style');
        });

        function confirm_submit(book_id, comment_id) {
            // 从 ckeditor 中取值
            let content = CKEDITOR.instances['id_content'].getData();
            // 调用 ajax 与后端交换数据
            $.ajax({
                url: '/comment/' + book_id + '/' + comment_id,
                type: 'POST',
                data: {content: content},
                // 成功回调
                success: function (e) {

                    // if(e === '200 OK'){
                    //     parent.location.reload();
                    // }
                    console.log(e)

                    if (e.code === '200 OK') {
                        // 调用父页面的函数
                        parent.post_reply_and_show_it(e.comment_id);
                    }
                }
            });
        }
    </script>
{% endblock %}

web/templates/loginEmail.html
{% extends 'layout/basic.html' %}
{% block title %}邮件登录{% endblock %}
{% load static %}
{% block css %}
    <link rel="stylesheet" href="{% static 'css/account.css' %}">
    <style>
        .error-msg {
            color: red;
            position: absolute;
            font-size: 13px;
        }
    </style>
{% endblock %}



{% block content %}
    <div class="account">
        <div class="title">邮箱登录</div>
        <form id="emailForm" method="POST" novalidate>
            {% csrf_token %}
            {% for field in form %}
                {% if field.name == 'code' %}
                    <div class="form-group">
                        <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                        <div class="row">
                            <div class="col-xs-7">
                                {{ field }}
                                <span class="error-msg"></span>
                            </div>
                            <div class="col-xs-5">
                                <input id="btnEmail" type="button" class="btn btn-default" value="点击获取验证码">
                            </div>
                        </div>
                    </div>
                {% else %}
                    <div class="form-group">

                        <label for="{{ field.id_for_label }}">{{ field.label }}</label>

                        {#                        <input type="password" class="form-control" placeholder="请输入新密码" autocomplete="off">#}
                        {{ field }}
                        <span class="error-msg"></span>
                    </div>
                {% endif %}
            {% endfor %}
            <div>
                <div style="float: right;">
                    <a href="{% url 'login' %}">用户名密码登录?</a>
                </div>
            </div>
            <div class="row">
                <div class="col-xs-3">
                    <input id="btnSubmit" type="button" class="btn btn-primary" value="登  录"/>
                </div>
            </div>
        </form>
    </div>




{% endblock %}




{% block js %}
    <script>
        $(function () {
            bindClickBtnEmail();
            bindClickSubmit();

        })

        //展现显现错误提示信息
        function bindClickBtnEmail() {
            $('#btnEmail').click(function () {

                $('.error-msg').empty();

                // 获取用户输入的手机号
                // 找到输入框的ID，根据ID获取值，如何找到手机号的那个ID？
                var email = $('#id_email').val();

                // 发送ajax请求，把手机号发送过去
                $.ajax({
                    url: "{% url 'send_email' %}", // 等价于 /send/sms/
                    type: "GET",
                    data: {email: email, tpl: "login"},
                    dataType: "JSON", // 将服务端返回的数据反序列化为字典
                    success: function (res) {
                        // ajax请求发送成功之后，自动执行的函数； res就是后端返回的值
                        if (res.status) {
                            sendEmailRemind();
                            console.log(res)
                        } else {
                            // 错误信息
                            // console.log(res); // {status:False, error:{ mobile_phone: ["错误信息"，],code: ["错误信息"，] }  }
                            $.each(res.error, function (key, value) {
                                $("#id_" + key).next().text(value[0]);
                            })
                        }
                    }
                })

            })
        }


        function bindClickSubmit() {
            $('#btnSubmit').click(function () {
                $('.error-msg').empty()
                $.ajax({
                    url: "{% url 'login_email' %}",
                    type: 'POST',
                    data: $('#emailForm').serialize(),
                    dataType: 'JSON',
                    success: function (res) {
                        if (res.status) {
                            location.href = res.data
                        } else {
                            console.log(res)
                            console.log(res.data)
                            $.each(res.error, function (key, value) {
                                console.log(key, value)
                                $("#id_" + key).next().text(value[0]);
                            })

                        }
                    }

                })
            })
        }

        function sendEmailRemind() {
            var $emailBtn = $('#btnEmail');
            $emailBtn.prop('disabled', true); // 禁用
            var time = 60;
            var remind = setInterval(function () {
                $emailBtn.val(time + '秒重新发送');
                time = time - 1;
                if (time < 1) {
                    clearInterval(remind);
                    $emailBtn.val('点击获取验证码').prop('disabled', false);
                }
            }, 1000)

        }

    </script>


{% endblock %}

web/templates/personal.html
{% extends 'layout/personbase.html' %}
{% load static %}

{% block title %} 首页 {% endblock %}

{% block css %}
    <link rel="stylesheet" href="{% static 'css/firstpage.css' %}">
    <style>
    .fontcolor{
        color: white;
    }
     .fontcolor:hover{
        color: #84f8e7;
    }

    </style>
{% endblock %}

{% block content %}
    {% load book_info %}
    <div class="qdp-wrapper">
        <div class="personal-sideBar" data-l1="2">
            <ul class="sideBar-group">
                <li class="active">
                    <a href="{% url 'firstpage' %}" class="sideBar-list-a"><i class="iconfont icon-home"></i>首页</a>
                </li>
                <li class="">
                    <a href="" class="sideBar-list-a" >账务中心</a>
                </li>
                <li class="">
                    <a href="" class="sideBar-list-a" >我的票夹</a>
                </li>
                <li class="">
                    <a href="{% url 'mybookcomm' %}" class="sideBar-list-a" >我的书评</a>
                </li>
            </ul>
        </div>

        <!-- 首页 页面 -->
        <div class="qdp-content home-content" >

            <div class="home-user-wrapper qdp-border" >
                <div class="home-user-avatar" >
                    <a href="{% url 'setting' user.id%}" class="fontcolor user-avatar-a">
                        <img class="user-avatar-img"
                             src="{{ MEDIA_URL }}{{user.icon }}"
                             alt="{{ user.name.username }}的头像"></a>
                    <a href="" target="_blank" class="home-user-vip icon user-level-cy"></a>
                </div>
                <div class="home-user">
                    <h3><a class="fontcolor" href="{% url 'setting' user.id%}" >{{ user.name.username }}</a><a href="" class="home-user-level">LV {{ user.level }}</a></h3>
                    <div class="home-user-data">
                        <span id="elFriendGuide" style="height:56px;display:inline-block;">
                            <a href="" class="fontcolor mr12">关注
                                <b class="fontcolor home-user-b">0</b>
                            </a>
                            <a href="" class="fontcolor mr12 ml12">粉丝 <b class="home-user-b fontcolor">0</b></a></span></div>
                </div>
            </div>
            <ul class="qdp-border home-msg-wrapper">
                <li class="home-msg">
                    <div class="home-msg-title"><b>账户余额</b></div>
                    <div class="home-msg-data"><a href="" ><b
                            class="home-msg-b">{{ user.dianbi }}</b>点币</a></div>
                    <a class="home-msg-more blue elPayBtn j_QQLiveE" href="" target="_blank">充值</a>
                </li>
                <li class="home-msg" >
                    <div class="home-msg-title"><b>我的票夹</b></div>
                    <div class="home-msg-data"><a href="/ticketbox" ><b
                            class="home-msg-b home-msg-num">0</b>月票&nbsp;·&nbsp;<span class="home-msg-num">1</span>推荐票</a>
                    </div>
                    <a class="home-msg-more blue" href="" >立即查看</a>
                </li>
                <li class="home-msg" >
                    <div class="home-msg-title"><b>我的书架</b></div>
                    <div class="home-msg-data"><a href="{% url 'bookshelf' %}" ><b class="home-msg-b">{{ user.name.myviewbook_set.count }}</b>本藏书</a>
                    </div>
                    <a class="home-msg-more blue" href="{% url 'bookshelf' %}" >立即查看</a>
                </li>
                <li class="home-msg" data-l3="2">
                    <div class="home-msg-title"><b>我的书单</b></div>
                    <div class="home-msg-data"><a href="" target="_blank"><b class="home-msg-b">1</b>个关注</a></div>
                    <a class="home-msg-more blue" href="" target="_blank">立即查看</a>
                </li>
            </ul>
        </div>
    </div>

{% endblock %}
{% block js %}
    <script>

    </script>



{% endblock %}

web/templates/setting.html
{% extends 'layout/personbase.html' %}
{% load static %}

{% block title %} 用户登录 {% endblock %}


{% block css %}
    <link rel="stylesheet" href="{% static 'css/account.css' %}">
    <style>

    </style>
{% endblock %}


{% block content %}
    <div class="account">
        <div class="title">用户信息</div>
        <form enctype="multipart/form-data" method="POST" action="{% url 'setting' id %}" novalidate>
            {% csrf_token %}
            <div>
                <div>
                    <label for="{{ form.icon.id_for_label }}">{{ form.icon.label }}</label>
                     <img style="height: 80px;width: 80px;border-radius: 80px" class="avatar-show" src="http://127.0.0.1:8000/media/{{ icon }}" alt="归云沐沐的头像">
                                   {{ form.icon }}
                </div>
                <div >
                    <label for="{{ form.sex.id_for_label }}">{{ form.sex.label }}</label>
                    {{ form.sex }}

                </div>
                <div>
                     <label for="{{ form.gory.id_for_label }}">{{ form.gory.label }}</label>
                    {{form.gory}}
                </div>
                <div style="height: 300px">
                     <label for="{{ form.introduction.id_for_label }}">{{ form.introduction.label }}</label>
                    {{form.introduction}}
                </div>

            </div>

            <div class="row">
                <div class="col-xs-3">
                    <input type="submit" class="btn btn-primary" value="提  交"/>
                </div>
            </div>
        </form>
    </div>
{% endblock %}


{% block js %}
    <script>

    </script>
{% endblock %}