notice/urls.py
from django.urls import path,re_path
# 引入views.py
from . import views

app_name = 'notice'

urlpatterns = [
    # 通知列表

re_path(r'^personal/update/$', views.CommentNoticeUpdateView.as_view(), name='readed'),
re_path(r'^personal/message/$',views.Allmessages,name='message'),
]

scrapy_django/urls.py
from django.contrib import admin
from django.urls import re_path,include,path
# from BookList.views import *
import notifications.urls
from django.conf import settings  # 此行是新增
from django.conf.urls.static import static  # 此行是新增
urlpatterns = [
    # re_path(r'^BookList/',include(('BookList.urls','BookList'),namespace='BookList')),
path('admin/', admin.site.urls),
    re_path(r'^', include('web.urls')),
path('ckeditor/', include('ckeditor_uploader.urls')),
   re_path('^inbox/notifications/', include(notifications.urls, namespace='notifications')),
    path('notice/', include('notice.urls', namespace='notice')),
    # path(r'^send/sms/', send_sms),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

web/urls.py
from django.contrib import admin
from django.urls import re_path,path,include
from web.views import account,home,comment,personal
from django.conf import settings
from django.conf.urls.static import static

from django.views.static import serve # 导入媒体文件资源
urlpatterns = [
    re_path(r'^register/$', account.register,name='register'),
re_path(r'^send/email/$', account.send_email,name='send_email'),
    re_path(r'^login/email/$', account.login_email, name='login_email'),
re_path(r'^login/$', account.Login, name='login'),
re_path(r'^image/code/$', account.image_code, name='image_code'),
re_path(r'^index/$',home.Lookbook,name='index'),
re_path(r'^logout/$', account.logout, name='logout'),
re_path(r'^book/(?P<id>\d+)$', home.Bookdetail, name='book_detail'),
re_path(r'^author/(?P<id>\d+)$', home.Authordetail, name='author_detail'),
# ,path('book/<str:id>',home.Bookdetail,name='book_detail')
# path(r'^send/sms/', send_sms),path('detail/<str:name>',Bookdetail,name='detail'),
path('type/<str:type>',home.Type,name='type'),
path('category/<str:category>',home.Category,name='category'),
path('state/<str:state>',home.State,name='state'),
re_path(r'^collection/$',home.Collection,name='collection'),
re_path(r'^popularity/$',home.Popularity,name='popularity'),
re_path(r'^word/$',home.Word,name='word'),

# re_path(r'^rank/(?P<url>\w+)/$',home.Rank,name='rank'),
re_path(r'^rank/word$',home.Rank,name='rank'),
re_path(r'^rank/recommend/$',home.Rank_tuijian,name='tuijian'),
re_path(r'^rank/yuepiao/$',home.Rank_yuepiao,name='yuepiao'),
re_path(r'^rank/vipcollection$',home.Rank_vipcollection,name='vipcollection'),

re_path(r'^end/$',home.End,name='end'),
re_path(r'^free/$',home.Free,name='free'),

re_path(r'^search/$',home.Search,name='search'),

    path('comment/<int:book_id>',comment.Comments , name='comment'),
    re_path(r'^reply/(?P<book_id>\d+)/(?P<parent_comment_id>\d+)/$', comment.Comments, name='reply'),
    # path('reply/<int:book_id>/<int:parent_comment_id>', comment.Comment, name='reply'),
    re_path(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}),
    # 图片文件路径，这里要注意，之前已经在setting.py文件处设置了媒体文件路径的别名是：MEDIA_URL = "/files/" ，所以这里的路由要保持一致




re_path(r'^personal/firstpage/$',personal.FirstPage,name='firstpage'),
# re_path(r'^personal/bookshelf/$',personal.BookShelf,name='bookshelf'),
re_path(r'^personal/bookshelf/$',personal.BookShelf.as_view(),name='bookshelf'),

re_path(r'^personal/mybookcomm/$',comment.my_book_comm,name='mybookcomm'),


re_path(r'^setting/(?P<id>\d+)$',personal.Settings.as_view(),name='setting'),

]
# urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

notice/models.py
from django.db import models

# Create your models here.

notice/views.py
from django.shortcuts import render, redirect

from django.views import View
from django.views.generic import ListView
from django.contrib.auth.mixins import LoginRequiredMixin

from web.models import *

def Allmessages(request):
    unnotices = Messages.objects.filter(receiver=request.noval.user).filter(is_read=False)
    notices = Messages.objects.filter(receiver=request.noval.user).filter(is_read=True)
    return render(request,'notice/message.html',{'unnotices':unnotices,'notices':notices})
# class CommentNoticeListView(ListView):
#     """通知列表"""
#     # 上下文的名称
#     context_object_name = 'notices'
#     # 模板位置
#     template_name = 'notice/message.html'
#
#     #重写init，赋予request。noval
#
#     def __init__(self, request, *args, **kwargs):
#         super().__init__(*args, **kwargs)
#         self.request = request
#     # 未读通知的查询集
#     @classmethod
#     def get_queryset(self):
#
#         return self.request.noval.user.notifications.unread()
# def msg_all_view(request):
#     msg_list = Messages.objects.filter(receiver = request.user)
#     return render(request, 'comment/msg_list.html',{'msg_list':msg_list})


# def msg_unread_view(request):
#
#     msg_list2 = []
#     for msg in msg_list:
#         if msg.is_read == False:
#             msg_list2.append(msg)
#
#     return render(request, 'comment/msg_list.html',{'msg_list':msg_list2})

class CommentNoticeUpdateView(View):
    """更新通知状态"""
    # 处理 get 请求
    def mark_all_as_read(self, recipient=None):
        queryset=Messages.objects.all()
        if  recipient:
            queryset = queryset.filter(receiver=recipient)
        for i in queryset:
            i.is_read=True
        return queryset.bulk_update(queryset,['is_read'])

    def mark_as_read(self,instance):
        if not instance.is_read:
            instance.is_read = True
            instance.save()

    def get(self, request):
        # 获取未读消息
        notice_id = request.GET.get('notice_id')
        # 更新单条通知
        if notice_id:
            book = Books.objects.get(id=request.GET.get('book_id'))
            self.mark_as_read(Messages.objects.get(id=notice_id))
            return redirect(book)
        # 更新全部通知
        else:
            self.mark_all_as_read(request.noval.user)
            return redirect('notice:message')

web/templates/notice/message.html
{% extends 'layout/personbase.html' %}
{% load static %}

{% block title %} 首页 {% endblock %}

{% block css %}
    <link rel="stylesheet" href="{% static 'css/firstpage.css' %}">
    <style>
        .length {
            width: 450px;
        }

        .dis {
            display: flex;
        }
        .height{

            height: 200px;
        }
    </style>
{% endblock %}

{% block content %}
    {% load book_info %}
    <div class="container">
        <div class="row mt-4 ml-4">
            <a href="{% url 'notice:readed' %}" class="btn btn-warning" role="button">一键已读</a>
        </div>
        <!-- 未读通知列表 -->
        <div class="row mt-2 ml-4 height pre-scrollable">
            <ul class="list-group">
            {% if unnotices %}
            {% for notice in unnotices %}
                    <li class="list-group-item dis" id="notice_link">
                        <a class="dis" href="{% url "notice:readed" %}?book_id={{ notice.comment.book.id }}&notice_id={{ notice.id }}"
                               target="_blank">
                        <div class="length">
                            <span style="margin-right: 5px;color: #ce8483">{{ notice.comment.user.username }}</span>
                            在 <span style="margin: 5px;color: #1ecfa7">{{ notice.comment.book.name }}</span> 中回复了你。
                        </div>
                        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{{ notice.create_date|date:"Y/m/d H:i" }}
                        <span style="margin-left: 100px">{{ notice.comment.content|limit_comment:20 }}</span>
                    </a>
                    </li>
                {% endfor %}
                {% else %}
                <div style="margin: 100px;font-size: 23px">暂无未读消息</div>
            {% endif %}

            </ul>
        </div>
    <div class="row mt-2 ml-4">
            <ul class="list-group">
            <div>历史消息</div>
            {% if notices %}
            {% for notice in notices %}
                    <li class="list-group-item dis" id="notice_link">
                        <div class="length">
                            <a href="{% url "notice:readed" %}?book_id={{ notice.comment.book.id }}&notice_id={{ notice.id }}"
                               target="_blank"
                            ></a>
                            <a href="">
                                {#                    {% url '' notice.comment.user.id %}#}
                                {{ notice.sender.username }}
                            </a>
                            在
                            <a href="{% url 'book_detail' notice.comment.book.id %}">{{ notice.comment.book.name }}</a>
                            中回复了你。
                        </div>
                        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{{ notice.create_date|date:"Y/m/d H:i" }}

                        <a href="">
                            <span style="margin-left: 100px">{{ notice.comment.content|limit_comment:20 }}</span>
                        </a>
                    </li>
                {% endfor %}
                {% else %}
                <div style="margin: 100px;font-size: 23px">暂无更多消息</div>
            {% endif %}

            </ul>
        </div>
    </div>


{% endblock %}
{% block js %}
    <script>

    </script>



{% endblock %}